// Artifact vocabulary for WD-40: what a target is, which group it belongs to,
// and how a size reads. Discovery lives in `discover`, measurement in `sizes`.
// Exports: `TargetDir`, `ArtifactKind`, `ArtifactGroup`, `human_size`,
// `sizes_may_overlap`. Deps: std only.

use std::path::PathBuf;
use std::time::SystemTime;

/// True when any target lives under a shared cargo target root. `aid` seeds
/// those per-session dirs with `cp -Rc` (APFS clone), so their reported sizes
/// share physical blocks and summing them overstates what a delete returns.
/// See docs/apfs-clone-overcount.md.
pub fn sizes_may_overlap(paths: &[PathBuf]) -> bool {
    paths.iter().any(|path| {
        path.components()
            .any(|component| component.as_os_str() == ".cargo-target")
    })
}

#[derive(Clone)]
pub struct TargetDir {
    pub path: PathBuf,
    pub size_bytes: u64,
    pub last_modified: SystemTime,
    pub kind: ArtifactKind,
}

#[derive(Clone, Copy)]
pub enum ArtifactKind {
    RustTarget,
    NodeModules,
    BuildOutput,
    Cache,
    TmpTarget,
}

impl ArtifactKind {
    pub fn label(self) -> &'static str {
        match self {
            Self::RustTarget => "target",
            Self::NodeModules => "node_modules",
            Self::BuildOutput => "build",
            Self::Cache => "cache",
            Self::TmpTarget => "tmp-target",
        }
    }

    pub fn group(self) -> ArtifactGroup {
        match self {
            Self::RustTarget | Self::TmpTarget => ArtifactGroup::Rust,
            Self::NodeModules => ArtifactGroup::NodeModules,
            Self::BuildOutput => ArtifactGroup::BuildOutput,
            Self::Cache => ArtifactGroup::Caches,
        }
    }
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum ArtifactGroup {
    Rust,
    NodeModules,
    BuildOutput,
    Caches,
}

/// What each group scans for, shown in its info panel.
const RUST_HELP: &str = "\
Scans for Rust compilation artifacts:

\u{2022} target/ \u{2014} Cargo build output
  Detected by: contains debug/ or release/ subdirectory

\u{2022} /tmp/*-target, /tmp/*-target-*, /tmp/cc-target-* \u{2014}
  Temporary Cargo build dirs (Claude Code & ad-hoc CARGO_TARGET_DIR)

\u{2022} ~/.cargo-target/*/ \u{2014} Per-project dirs under shared CARGO_TARGET_DIR root

\u{2022} ~/.aid/worktrees/<repo>/<branch>/target \u{2014}
  Cargo targets inside aid-managed git worktrees

Safe to delete \u{2014} regenerated by `cargo build`.";

const NODE_HELP: &str = "\
Scans for Node.js dependency directories:

\u{2022} node_modules/ \u{2014} npm/yarn installed packages
  Detected by: contains .package-lock.json or .yarn-integrity

Safe to delete \u{2014} regenerated by `npm install` or `yarn install`.";

const BUILD_HELP: &str = "\
Scans for build tool output directories:

\u{2022} .next/ \u{2014} Next.js build cache
  Detected by: contains cache/ or static/ subdirectory

\u{2022} dist/ \u{2014} Common build output (Vite, webpack, TypeScript)
\u{2022} build/ \u{2014} Build output (CRA, Gradle, PlatformIO)
  Detected by: parent has package.json, Cargo.toml, build.gradle, or platformio.ini

Safe to delete \u{2014} regenerated by running the build command.";

const CACHE_HELP: &str = "\
Scans for regenerable developer caches:

\u{2022} DerivedData/ \u{2014} Xcode build cache
\u{2022} ModuleCache.noindex/ \u{2014} Xcode module cache
\u{2022} CoreSimulator/Devices/*/data/Library/Caches/ \u{2014} simulator caches
\u{2022} ~/.npm/_cacache, pnpm and Yarn stores
\u{2022} Homebrew cache dirs

Safe to delete \u{2014} rebuilds may need network downloads.";

impl ArtifactGroup {
    pub const ALL: &[ArtifactGroup] = &[
        ArtifactGroup::Rust,
        ArtifactGroup::NodeModules,
        ArtifactGroup::BuildOutput,
        ArtifactGroup::Caches,
    ];

    pub fn label(self) -> &'static str {
        match self {
            Self::Rust => "Rust",
            Self::NodeModules => "Node Modules",
            Self::BuildOutput => "Build Output",
            Self::Caches => "Caches",
        }
    }

    /// SF Symbol shown next to the group header.
    pub fn symbol(self) -> &'static str {
        match self {
            Self::Rust => "gearshape.2",
            Self::NodeModules => "shippingbox",
            Self::BuildOutput => "hammer",
            // externaldrive.badge.clock does not exist on every macOS the app runs on,
            // and a missing symbol draws nothing at all.
            Self::Caches => "clock.arrow.circlepath",
        }
    }

    pub fn tag(self) -> isize {
        match self {
            Self::Rust => 0,
            Self::NodeModules => 1,
            Self::BuildOutput => 2,
            Self::Caches => 3,
        }
    }

    pub fn from_tag(tag: isize) -> Option<Self> {
        match tag {
            0 => Some(Self::Rust),
            1 => Some(Self::NodeModules),
            2 => Some(Self::BuildOutput),
            3 => Some(Self::Caches),
            _ => None,
        }
    }

    pub fn description(self) -> &'static str {
        match self {
            Self::Rust => RUST_HELP,
            Self::NodeModules => NODE_HELP,
            Self::BuildOutput => BUILD_HELP,
            Self::Caches => CACHE_HELP,
        }
    }
}

pub fn human_size(bytes: u64) -> String {
    let mut value = bytes as f64;
    let mut unit = 0;
    let units = ["B", "K", "M", "G", "T"];
    while value >= 1024.0 && unit < units.len() - 1 {
        value /= 1024.0;
        unit += 1;
    }
    if unit == 0 {
        format!("{}{}", bytes, units[unit])
    } else {
        format!("{:.1}{}", value, units[unit])
    }
}

#[cfg(test)]
mod tests {
    use super::sizes_may_overlap;
    use std::path::PathBuf;

    #[test]
    fn shared_cargo_root_targets_can_overlap() {
        let paths = vec![PathBuf::from("/Users/x/.cargo-target/proj/session-a")];
        assert!(sizes_may_overlap(&paths));
    }

    #[test]
    fn ordinary_project_targets_do_not_overlap() {
        let paths = vec![
            PathBuf::from("/Users/x/Develop/proj/target"),
            PathBuf::from("/Users/x/Develop/web/node_modules"),
        ];
        assert!(!sizes_may_overlap(&paths));
    }
}
