// Dev artifact scanner for WD-40.
// Finds Rust targets, node_modules, build dirs and reports size/mtime.
// Phase 1: discover directories (fast). Phase 2: compute sizes in parallel.
use crate::config::Config;
use getattrlistbulk::{DirReader, ObjectType, RequestedAttributes};
use std::path::{Path, PathBuf};
use std::time::SystemTime;
use walkdir::{DirEntry, WalkDir};

pub struct TargetDir {
    pub path: PathBuf,
    pub size_bytes: u64,
    pub last_modified: SystemTime,
    pub kind: ArtifactKind,
}

#[derive(Clone, Copy)]
pub enum ArtifactKind {
    RustTarget,
    NodeModules,
    BuildOutput,
    CcTarget,
}

impl ArtifactKind {
    pub fn label(self) -> &'static str {
        match self {
            Self::RustTarget => "target",
            Self::NodeModules => "node_modules",
            Self::BuildOutput => "build",
            Self::CcTarget => "cc-target",
        }
    }

    pub fn group(self) -> ArtifactGroup {
        match self {
            Self::RustTarget | Self::CcTarget => ArtifactGroup::Rust,
            Self::NodeModules => ArtifactGroup::NodeModules,
            Self::BuildOutput => ArtifactGroup::BuildOutput,
        }
    }
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum ArtifactGroup {
    Rust,
    NodeModules,
    BuildOutput,
}

impl ArtifactGroup {
    pub const ALL: &[ArtifactGroup] = &[
        ArtifactGroup::Rust,
        ArtifactGroup::NodeModules,
        ArtifactGroup::BuildOutput,
    ];

    pub fn label(self) -> &'static str {
        match self {
            Self::Rust => "Rust",
            Self::NodeModules => "Node Modules",
            Self::BuildOutput => "Build Output",
        }
    }

    pub fn tag(self) -> isize {
        match self {
            Self::Rust => 0,
            Self::NodeModules => 1,
            Self::BuildOutput => 2,
        }
    }

    pub fn from_tag(tag: isize) -> Option<Self> {
        match tag {
            0 => Some(Self::Rust),
            1 => Some(Self::NodeModules),
            2 => Some(Self::BuildOutput),
            _ => None,
        }
    }

    pub fn description(self) -> &'static str {
        match self {
            Self::Rust => "\
Scans for Rust compilation artifacts:

\u{2022} target/ \u{2014} Cargo build output
  Detected by: contains debug/ or release/ subdirectory

\u{2022} /tmp/cc-target-* \u{2014} Temporary Cargo build dirs (Claude Code sessions)

Safe to delete \u{2014} regenerated by `cargo build`.",

            Self::NodeModules => "\
Scans for Node.js dependency directories:

\u{2022} node_modules/ \u{2014} npm/yarn installed packages
  Detected by: contains .package-lock.json or .yarn-integrity

Safe to delete \u{2014} regenerated by `npm install` or `yarn install`.",

            Self::BuildOutput => "\
Scans for build tool output directories:

\u{2022} .next/ \u{2014} Next.js build cache
  Detected by: contains cache/ or static/ subdirectory

\u{2022} dist/ \u{2014} Common build output (Vite, webpack, TypeScript)
\u{2022} build/ \u{2014} Build output (CRA, Gradle, PlatformIO)
  Detected by: parent has package.json, Cargo.toml, build.gradle, or platformio.ini

Safe to delete \u{2014} regenerated by running the build command.",
        }
    }
}

/// Phase 1: discover artifact directories (fast, <1s).
pub fn scan_discover(config: &Config) -> Vec<TargetDir> {
    let types: Vec<&str> = config.artifact_types.iter().map(|s| s.as_str()).collect();
    let dirs: Vec<&PathBuf> = config.scan_dirs.iter().filter(|d| d.exists()).collect();
    let mut found: Vec<TargetDir> = std::thread::scope(|s| {
        let handles: Vec<_> = dirs
            .iter()
            .map(|dir| {
                let types = &types;
                let artifact_types = &config.artifact_types;
                let max_depth = config.max_depth;
                s.spawn(move || {
                    let mut local = Vec::new();
                    let walker = WalkDir::new(dir).max_depth(max_depth);
                    for entry in walker
                        .into_iter()
                        .filter_entry(|e| !should_skip(e, artifact_types))
                        .filter_map(Result::ok)
                    {
                        if entry.depth() == 0 || !entry.file_type().is_dir() {
                            continue;
                        }
                        let name = entry.file_name().to_string_lossy();
                        if !types.iter().any(|t| *t == name) {
                            continue;
                        }
                        if !is_dev_artifact(entry.path(), &name) {
                            continue;
                        }
                        let last_modified = entry
                            .metadata()
                            .ok()
                            .and_then(|m| m.modified().ok())
                            .unwrap_or(SystemTime::UNIX_EPOCH);
                        let kind = match name.as_ref() {
                            "target" => ArtifactKind::RustTarget,
                            "node_modules" => ArtifactKind::NodeModules,
                            _ => ArtifactKind::BuildOutput,
                        };
                        local.push(TargetDir {
                            path: entry.into_path(),
                            size_bytes: 0,
                            last_modified,
                            kind,
                        });
                    }
                    local
                })
            })
            .collect();
        handles
            .into_iter()
            .flat_map(|h| h.join().unwrap_or_default())
            .collect()
    });
    collect_tmp_targets(&mut found);
    found
}

/// Phase 2: compute sizes in parallel for already-discovered targets.
pub fn scan_sizes(targets: &mut Vec<TargetDir>) {
    let paths: Vec<&Path> = targets.iter().map(|td| td.path.as_path()).collect();
    let sizes: Vec<u64> = std::thread::scope(|s| {
        let handles: Vec<_> = paths
            .iter()
            .map(|p| s.spawn(|| dir_size(p)))
            .collect();
        handles
            .into_iter()
            .map(|h| h.join().unwrap_or(0))
            .collect()
    });
    for (td, size) in targets.iter_mut().zip(sizes) {
        td.size_bytes = size;
    }
    targets.sort_by(|a, b| b.size_bytes.cmp(&a.size_bytes));
}

/// Directories that never contain dev artifacts — skip to avoid slow traversal.
const SKIP_DIRS: &[&str] = &[
    // Media & personal
    "Music", "Movies", "Photos", "Pictures",
    // macOS system
    "Library", "Applications", "System",
    // iCloud & cloud storage
    "Mobile Documents", "iCloud Drive", "Google Drive", "OneDrive", "Dropbox",
    // Network & external volumes
    "Volumes",
];

fn should_skip(entry: &DirEntry, artifact_types: &[String]) -> bool {
    if entry.depth() == 0 || !entry.file_type().is_dir() {
        return false;
    }
    // Skip symlinks — don't follow into network mounts or iCloud aliases
    if entry.path_is_symlink() {
        return true;
    }
    let name = entry.file_name().to_string_lossy();
    // Skip hidden dirs (except known artifact types like .next)
    if name.starts_with('.') && !artifact_types.iter().any(|t| t == name.as_ref()) {
        return true;
    }
    // Skip non-dev directories (media, cloud, system)
    if SKIP_DIRS.iter().any(|&s| s == name.as_ref()) {
        return true;
    }
    // Don't descend INTO artifact directories — we only need the dir itself, not its children.
    if let Some(parent_name) = entry.path().parent().and_then(|p| p.file_name()) {
        let pname = parent_name.to_string_lossy();
        if artifact_types.iter().any(|t| t == pname.as_ref()) {
            return true;
        }
    }
    false
}

/// Validate that a directory is actually a dev artifact, not a false positive.
fn is_dev_artifact(path: &Path, name: &str) -> bool {
    match name {
        "target" => path.join("debug").is_dir() || path.join("release").is_dir(),
        "node_modules" => {
            path.join(".package-lock.json").is_file()
                || path.join(".yarn-integrity").is_file()
        }
        ".next" => path.join("cache").is_dir() || path.join("static").is_dir(),
        "dist" | "build" => path.parent().is_some_and(|p| {
            p.join("package.json").is_file()
                || p.join("Cargo.toml").is_file()
                || p.join("build.gradle").is_file()
                || p.join("platformio.ini").is_file()
        }),
        _ => false,
    }
}

/// Collect /tmp/cc-target-* directories (no size computation).
fn collect_tmp_targets(found: &mut Vec<TargetDir>) {
    let tmp = Path::new("/tmp");
    let entries = match std::fs::read_dir(tmp) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.filter_map(Result::ok) {
        let name = entry.file_name();
        if !name.to_string_lossy().starts_with("cc-target-") {
            continue;
        }
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let last_modified = entry
            .metadata()
            .ok()
            .and_then(|m| m.modified().ok())
            .unwrap_or(SystemTime::UNIX_EPOCH);
        found.push(TargetDir {
            path,
            size_bytes: 0,
            last_modified,
            kind: ArtifactKind::CcTarget,
        });
    }
}

/// Compute directory size using macOS getattrlistbulk for bulk metadata reads.
/// Falls back to walkdir+stat if the bulk API fails.
fn dir_size(path: &Path) -> u64 {
    dir_size_bulk(path).unwrap_or_else(|| dir_size_fallback(path))
}

const BULK_ATTRS: RequestedAttributes = RequestedAttributes {
    name: true,
    object_type: true,
    size: true,
    alloc_size: false,
    modified_time: false,
    permissions: false,
    inode: false,
    entry_count: false,
};
const BULK_BUF: usize = 256 * 1024;

fn dir_size_bulk(path: &Path) -> Option<u64> {
    let mut total: u64 = 0;
    let mut dirs = vec![path.to_path_buf()];
    while let Some(dir) = dirs.pop() {
        let entries = DirReader::new(&dir)
            .attributes(BULK_ATTRS)
            .buffer_size(BULK_BUF)
            .follow_symlinks(false)
            .read()
            .ok()?;
        for result in entries {
            let entry = match result {
                Ok(e) => e,
                Err(_) => return None, // parse error — data may be corrupt, fall back
            };
            match entry.object_type {
                Some(ObjectType::Directory) => dirs.push(dir.join(&entry.name)),
                Some(ObjectType::Symlink) => {}
                _ => total += entry.size.unwrap_or(0),
            }
        }
    }
    Some(total)
}

fn dir_size_fallback(path: &Path) -> u64 {
    WalkDir::new(path)
        .into_iter()
        .filter_map(Result::ok)
        .filter_map(|entry| entry.metadata().ok())
        .map(|meta| meta.len())
        .sum()
}

pub fn human_size(bytes: u64) -> String {
    let mut value = bytes as f64;
    let mut unit = 0;
    let units = ["B", "K", "M", "G", "T"];
    while value >= 1024.0 && unit < units.len() - 1 {
        value /= 1024.0;
        unit += 1;
    }
    if unit == 0 {
        format!("{}{}", bytes, units[unit])
    } else {
        format!("{:.1}{}", value, units[unit])
    }
}
